{{ config(materialized='table') }}

with level_metrics as (
    -- From your first intermediate model (Starts, Ends, Ads)
    select * from {{ ref('int_level_events_joined') }}
),

churn_metrics as (
    -- From your second intermediate model (Player status)
    -- We filter for only the 'dropped' players here
    select 
        furthest_level,
        count(distinct player_id) as drop_users
    from {{ ref('int_player_churn_status') }}
    where is_dropped = 1
    group by 1
),

total_users_const as (
    -- Used for the Cumulative ARPU calculation
    select count(distinct player_id) as total_users 
    from {{ ref('stg_level_starts') }}
)

select
    m.level_number,
    m.started_users,
    m.completed_users,
    t.total_users,
    m.revenue,
    coalesce(c.drop_users, 0) as drop_users,

    -- 1. Performance Metrics
    round(safe_divide(m.completed_users, m.started_users) * 100, 2) as win_rate,
    round(100 - (safe_divide(m.completed_users, m.started_users) * 100), 2) as lose_rate,

    -- 2. Revenue Insights
    round(safe_divide(m.revenue, m.started_users), 4) as arpu_per_level,
    
    -- 3. Cumulative Calculations (The "Progression" View)
    -- This shows how much money a single player has generated by the time they reach this level
    sum(m.revenue) over (order by m.level_number asc) as cumulative_revenue,
    round(
        safe_divide(
            sum(m.revenue) over (order by m.level_number asc), 
            t.total_users
        ), 4
    ) as cumulative_arpu,

    -- 4. Churn Insights
    round(safe_divide(coalesce(c.drop_users, 0), m.started_users) * 100, 2) as drop_rate,
    -- current_timestamp
    current_timestamp() as dbt_updated_at
from level_metrics m
left join churn_metrics c 
    on m.level_number = c.furthest_level
cross join total_users_const t

order by m.level_number asc